### ISSUE TITLE
Not able to browse the library

### ISSUE THREAD

**Issue by SGudman** [anton-suprun/anki-raycast#1]
I am receiving an error message even though all troubleshooting steps were followed.

**Comment by anton-suprun** [comment]
> I am receiving an error message even though all troubleshooting steps were followed.

Hi,

Sorry to hear that! What is the error message you're receiving and what command / action are you performing ?

**Comment by SGudman** [comment]
> Sorry to hear that! What is the error message you're receiving and what command / action are you performing ? (Include as many details as much details as you can)

Hi, the action is "browse cards". Other actions are working fine. When I'm trying to browse cards it's providing me standard troubleshooting steps:
<img width="1062" alt="Screenshot 2024-08-14 at 22 41 33" src="https://github.com/user-attachments/assets/715d59df-643c-40cf-96a1-30d703d7481a">

**Comment by anton-suprun** [comment]
> 
> 
> > Sorry to hear that! What is the error message you're receiving and what command / action are you performing ? (Include as many details as much details as you can)
> 
> 
> 
> Hi, the action is "browse cards". Other actions are working fine. When I'm trying to browse cards it's providing me standard troubleshooting steps:
> 
> <img width="1062" alt="Screenshot 2024-08-14 at 22 41 33" src="https://github.com/user-attachments/assets/715d59df-643c-40cf-96a1-30d703d7481a">
> 
> 
> 
> 

Thanks for reporting! I'll investigate, try to re-create and hopefully fix the issue

Will keep you posted. 

Cheers!

**Comment by SGudman** [comment]
Hey!
Thank you! That's so cool that you're doing that; it's such a helpful add-on. I had been coming to the store, trying to find it, and finally, you released it!
Great work! Hats off to you!

**Comment by anton-suprun** [comment]
> Hey!
> 
> Thank you! That's so cool that you're doing that; it's such a helpful add-on. I had been coming to the store, trying to find it, and finally, you released it!
> 
> Great work! Hats off to you!

Thank you for the kind words; means a lot!! 🙏

Happy that you find it useful! 


To help me debug this:

- How many cards do you have in total (approximately)?

**Comment by SGudman** [comment]
There are 21500

**Comment by SGudman** [comment]
I can delete  some and give it a try

**Comment by anton-suprun** [comment]
> I can delete  some and give it a try

Ah I see (nice collection! )

No need to delete; I think the issue may be that the JS heap runs out of memory (must be reaching a memory limit) 

I've intended to set up paging (in progress) which should solve the issue of browsing cards for large collections but this may take a bit of time.

I will address this as soon as I have time.

Sorry for the inconvenience but until I add pagination to browsing cards,there may be no other quick fix :/

**Comment by anton-suprun** [comment]
> > I can delete  some and give it a try
> 
> Ah I see (nice collection! )
> 
> No need to delete; I think the issue may be that the JS heap runs out of memory (must be reaching a memory limit) 
> 
> I've intended to set up paging (in progress) which should solve the issue of browsing cards for large collections but this may take a bit of time.
> 
> I will address this as soon as I have time.
> 
> Sorry for the inconvenience but until I add pagination to browsing cards,there may be no other quick fix :/  

I had a few other things in the priority queue but will put this on top of the list!

**Comment by SGudman** [comment]
Thank you very much, perhaps it’s not worth giving this much attention, because after I mentioned the collection of 21,500 cards, I was shocked by the number myself. I went to check and found a board with 20,000 entries among them, deleted it, and now everything is working just fine. I couldn’t get into a good workflow before, so I didn’t accumulate a large number of entries. I hope this extension will help me. I also plan to store various code snippets and use it as a note-taking tool, since I couldn’t find anything in the store that would simply let me take notes and organize them into folders or assign tags. Native Snippets were the most convenient, but everything had to be kept in a jumble because there was no categorization feature.Thanks one more time!

**Comment by anton-suprun** [comment]
> Thank you very much, perhaps it’s not worth giving this much attention, because after I mentioned the collection of 21,500 cards, I was shocked by the number myself. I went to check and found a board with 20,000 entries among them, deleted it, and now everything is working just fine. I couldn’t get into a good workflow before, so I didn’t accumulate a large number of entries. I hope this extension will help me. I also plan to store various code snippets and use it as a note-taking tool, since I couldn’t find anything in the store that would simply let me take notes and organize them into folders or assign tags. Native Snippets were the most convenient, but everything had to be kept in a jumble because there was no categorization feature.Thanks one more time!

Ah I see; so this isn't a critical issue for now then?

If that's the case; I will prioritize other TODOs for now. Thanks for confirming the case for having pagination (I was going to originally add it but realized it would take a bit longer than just rendering everything in bulk).

Happy that it works now 😃

**Comment by SGudman** [comment]
> Ah I see; so this isn't a critical issue for now then?

I do not come across this issue as often now, but still encounter it sometimes. Empirically, I have noticed that the limit is somewhere around 1000 because boards with around 600 entries open without any problems, but when I try to open the parent board, which contains two boards with 600 each (a total of 1200), I receive an error.

**Comment by SGudman** [comment]
> I do not come across this issue as often now, but still encounter it sometimes. Empirically, I have noticed that the limit is somewhere around 1000 because boards with around 600 entries open without any problems, but when I try to open the parent board, which contains two boards with 600 each (a total of 1200), I receive an error.

This is quite tolerable, because all other functionality works perfectly, I just access boards with fewer entries. The only limitation is when you need to search for a word throughout the entire database if you’re not sure which board it should be in.

**Comment by anton-suprun** [comment]
> > I do not come across this issue as often now, but still encounter it sometimes. Empirically, I have noticed that the limit is somewhere around 1000 because boards with around 600 entries open without any problems, but when I try to open the parent board, which contains two boards with 600 each (a total of 1200), I receive an error.
> 
> 
> 
> This is quite tolerable, because all other functionality works perfectly, I just access boards with fewer entries. The only limitation is when you need to search for a word throughout the entire database if you’re not sure which board it should be in.

Okay; I will keep this issue open and address in next release :)

**Comment by anton-suprun** [comment]
Hi 👋 

The fix for the change was merged recently. (https://github.com/raycast/extensions/pull/14424)

Let me know if this issue persists despite the change I added

**Comment by SGudman** [comment]
Hello! I noticed that something had changed even before seeing your message and the issue did not appear again. Now everything is working very smoothly, thank you so very much!
